#!/bin/sh -efu
#
# Copyright (C) 2009  Alexey Gladkov <legion@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

. gear-update-sh-functions

check_source_type()
{
	local file_type

	file_type="$(file -b "$gear_update_source")"
	[ -n "${file_type##*Zip archive*}" ] ||
		return 0

	return 2
}

list_source()
{
	zipinfo -1 -- "$gear_update_source"
}

workdir=
cleanup_handler()
{
	[ -z "$workdir" -o ! -d "$workdir" ] ||
		rm -rf -- "$workdir"
}

unpack_source()
{
	install_cleanup_handler cleanup_handler
	workdir="$(mktemp -d "$PROG.XXXXXXXXX")"

	unzip -q "$gear_update_source" ${gear_update_subdir:+"$gear_update_subdir/*"} -d "$workdir"

	validate_destdir "$workdir/$gear_update_subdir" "$gear_update_destdir"
	update_destdir move "$workdir/$gear_update_subdir" "$gear_update_destdir"
}

gear_update_handler "$@"
