#!/bin/sh -efu
#
# Copyright (C) 2009  Alexey Gladkov <legion@altlinux.org>
# Copyright (C) 2009  Alexey I. Froloff <raorn@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

. gear-update-sh-functions

check_source_type()
{
	local file_type file_list

	file_type="$(file -b "$gear_update_source")"
	[ -z "${file_type##*tar archive*}" ] ||
		return 2

	file_list="$(tar -tf "$gear_update_source"| LC_COLLATE=C sort| tr '\n' ' ')"
	[ "$file_list" = "data.tar.gz metadata.gz " ] ||
		return 2

	file_type="$(tar -xOf "$gear_update_source" "data.tar.gz"| file -bz -)"
	[ -z "${file_type##*tar archive*}" ] ||
		return 2

	[ -z "$gear_update_all_subdirs" ] ||
		fatal "Cannot use --all for updating from a gem source."

	[ -z "$gear_update_subdir" ] ||
		fatal "Cannot use --subdir for updating from a gem source."

	return 0
}

list_source()
{
	# Ignore --subdir/--all options.
	printf '%s\n' "fake_gem_subdir/"
}

workdir=
cleanup_handler()
{
	[ -z "$workdir" -o ! -d "$workdir" ] ||
		rm -rf -- "$workdir"
}

unpack_source()
{
	install_cleanup_handler cleanup_handler
	workdir="$(mktemp -d "$PROG.XXXXXXXXX")"

	tar -xOf "$gear_update_source" "data.tar.gz"| tar -xzmf - -C "$workdir"

	validate_destdir "$workdir" "$gear_update_destdir"
	update_destdir move "$workdir" "$gear_update_destdir"
}

gear_update_handler "$@"
