#!/bin/sh -eu
#
# Copyright (C) 2011  Alexey Gladkov <legion@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

gear-command-rpmbuild \
	rpmbuild -bs --nodeps --define "_srcrpmdir $gear_workdir"

. gear-sh-functions

verbose="${gear_verbose-}"
rm -rf -- "$gear_outdir"

gear_unset_exported_vars
run_command "$@" --rebuild "$gear_workdir"/*.src.rpm
