#!/bin/sh -efu
#
# Copyright (C) 2009  Alexey Gladkov <legion@altlinux.org>
# Copyright (C) 2016  Dmitry V. Levin <ldv@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

. gear-update-sh-functions

check_source_type()
{
	local file_type

	file_type="$(file -b "$gear_update_source")"
	[ -n "${file_type##*tar archive*}" ] ||
		return 0

	file_type="$(file -bz "$gear_update_source")"
	[ -n "${file_type##*tar archive*}" ] ||
		return 0

	return 2
}

list_source()
{
	tar -tf "$gear_update_source"
}

unpack_source()
{
	install_cleanup_handler cleanup_workdir
	workdir="$(mktemp -d "$PROG.XXXXXXXXX")"

	tar -x -f "$gear_update_source" -C "$workdir" -- ${gear_update_subdir:+"$gear_update_subdir/"}
	chmod -R u+rwX,go-w -- "$workdir"

	validate_destdir "$workdir/$gear_update_subdir" "$gear_update_destdir"
	update_destdir move "$workdir/$gear_update_subdir" "$gear_update_destdir"
}

gear_update_handler "$@"
