#!/bin/sh -efu
#
# Copyright (C) 2009  Alexey Gladkov <legion@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

. gear-update-sh-functions

check_source_type()
{
	[ -d "$gear_update_source" ] ||
		return 2

	[ -z "$gear_update_all_subdirs" ] ||
		fatal "Cannot use --all for updating from a directory source."

	[ -z "$gear_update_subdir" ] ||
		fatal "Cannot use --subdir for updating from a directory source."
}

list_source()
{
	ls -d1 -- "$gear_update_source"
}

unpack_source()
{
	validate_destdir "$gear_update_source" "$gear_update_destdir"
	update_destdir copy "$gear_update_source" "$gear_update_destdir"
}

gear_update_handler "$@"
