#!/bin/sh -efu
#
# Copyright (C) 2006-2007  Dmitry V. Levin <ldv@altlinux.org>
# Copyright (C) 2008  Alexey Gladkov <legion@altlinux.org>
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

. gear-sh-functions

specfile="${gear_specfile##*/}"
verbose="${gear_verbose-}"

find "$gear_outdir" -maxdepth 1 -type f -printf '%f\0' |
	LC_COLLATE=C sort -uz |
	xargs -r0 tar --create --file="$gear_outfile" --directory="$gear_outdir" \
		--label="$specfile" --owner=root --group=root \
		--mode=u+w,go-w,go+rX $gear_tar_compress --

verbose "Created output tarball: $gear_outfile"

# Once tarball is created, its sources are no longer needed.
rm -rf -- "$gear_outdir"
run_command "$@" "$gear_outfile"
