#!/bin/sh -efu 
#
# input list of srpm files,
# output list of somewhat unique srpm files in buildtime order,
# same package name is assumed.

prev=

while read f; do
	rpmquery -p --qf '%{NAME}\t%{BUILDTIME}\t%{VERSION}\t%{RELEASE}' "$f" &&
		printf '\t%s\n' "$f"
done |
	sort -k1,1 -k2,2n -k3,4 |
	cut -f5 |
while read f; do
	[ -f "$f" -a -r "$f" ] ||
		continue
	if [ -n "$prev" ] &&
	   cmp -s "$prev" "$f"; then
		continue
	fi
	printf %s\\n "$f"
	prev="$f"
done
